version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: alx_postgres
    environment:
      POSTGRES_DB: alx_db
      POSTGRES_USER: alx_user
      POSTGRES_PASSWORD: alx_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: alx_redis
    ports:
      - "6379:6379"

      DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'alx_property',
        'USER': 'alx_user',
        'PASSWORD': 'alx_password',
        'HOST': 'localhost',  # or 'postgres' if running Django in Docker
        'PORT': '5432',
    }
}
